// lib/data/bus_data.dart
import '../models/bus_model.dart';

final List<BusModel> busList = [
  // --- বাস ১ - ২০ ---
  BusModel(
    nameEn: 'Shikor 1',
    nameBn: 'শিকর ১',
    fromEn: 'Banani',
    fromBn: 'বনানী',
    toEn: 'Kawran Bazar',
    toBn: 'কাওরান বাজার',
    fare: 21,
    stoppagesEn: ['Banani', 'Mohakhali', 'Kawran Bazar'],
    stoppagesBn: ['বনানী', 'মহাখালী', 'কাওরান বাজার'],
  ),
  BusModel(
    nameEn: 'Basumoti 2',
    nameBn: 'বাসুমতি ২',
    fromEn: 'Farmgate Bypass',
    fromBn: 'ফার্মগেট বাইপাস',
    toEn: 'Malibagh',
    toBn: 'মালিবাগ',
    fare: 22,
    stoppagesEn: ['Farmgate', 'Mogbazar', 'Malibagh'],
    stoppagesBn: ['ফার্মগেট', 'মগবাজার', 'মালিবাগ'],
  ),
  BusModel(
    nameEn: 'Shikor 3',
    nameBn: 'শিকর ৩',
    fromEn: 'Dhanmondi 27',
    fromBn: 'ধানমন্ডি ২৭',
    toEn: 'Banani Road',
    toBn: 'বনানী রোড',
    fare: 25,
    stoppagesEn: [
      'Dhanmondi 27',
      'Panthapath',
      'Malibagh',
      'Banani Road',
    ],
    stoppagesBn: [
      'ধানমন্ডি ২৭',
      'পান্থপথ',
      'মালিবাগ',
      'বনানী রোড',
    ],
  ),
  BusModel(
    nameEn: 'Diamond 4',
    nameBn: 'ডায়মন্ড ৪',
    fromEn: 'Banani',
    fromBn: 'বনানী',
    toEn: 'Uttara',
    toBn: 'উত্তরা',
    fare: 26,
    stoppagesEn: [
      'Banani',
      'Gulshan 2',
      'Jatrabari',
      'Savar Bazar',
      'Uttara',
    ],
    stoppagesBn: [
      'বনানী',
      'গুলশান ২',
      'যাত্রাবাড়ি',
      'সাভার বাজার',
      'উত্তরা',
    ],
  ),
  BusModel(
    nameEn: 'GreenLine 5',
    nameBn: 'গ্রিনলাইন ৫',
    fromEn: 'Malibagh',
    fromBn: 'মালিবাগ',
    toEn: 'Panthapath',
    toBn: 'পান্থপথ',
    fare: 40,
    stoppagesEn: ['Malibagh', 'Mirpur 2', 'Panthapath'],
    stoppagesBn: ['মালিবাগ', 'মিরপুর ২', 'পান্থপথ'],
  ),
  BusModel(
    nameEn: 'Bikalpa 6',
    nameBn: 'বিকল্প ৬',
    fromEn: 'Dhanmondi 27',
    fromBn: 'ধানমন্ডি ২৭',
    toEn: 'Shantinagar',
    toBn: 'শান্তিনগর',
    fare: 23,
    stoppagesEn: [
      'Dhanmondi 27',
      'Motijheel',
      'Paltan',
      'Uttarkhan',
      'Gulshan 2',
      'Shantinagar',
    ],
    stoppagesBn: [
      'ধানমন্ডি ২৭',
      'মতিঝিল',
      'পল্টন',
      'উত্তরখান',
      'গুলশান ২',
      'শান্তিনগর',
    ],
  ),
  BusModel(
    nameEn: 'Sunrise 7',
    nameBn: 'সানরাইজ ৭',
    fromEn: 'Mirpur 10',
    fromBn: 'মিরপুর ১০',
    toEn: 'Uttarkhan',
    toBn: 'উত্তরখান',
    fare: 30,
    stoppagesEn: [
      'Mirpur 10',
      'Gazipur',
      'Mirpur 1',
      'Uttara Sector 11',
      'Uttarkhan',
    ],
    stoppagesBn: [
      'মিরপুর ১০',
      'গাজীপুর',
      'মিরপুর ১',
      'উত্তরা সেক্টর ১১',
      'উত্তরখান',
    ],
  ),
  BusModel(
    nameEn: 'GreenLine 8',
    nameBn: 'গ্রিনলাইন ৮',
    fromEn: 'Mirpur 11',
    fromBn: 'মিরপুর ১১',
    toEn: 'Khilgaon',
    toBn: 'খিলগাঁও',
    fare: 38,
    stoppagesEn: [
      'Mirpur 11',
      'Badda',
      'Rampura',
      'Gulshan 2',
      'Khilgaon',
    ],
    stoppagesBn: [
      'মিরপুর ১১',
      'বাড্ডা',
      'রামপুরা',
      'গুলশান ২',
      'খিলগাঁও',
    ],
  ),
  BusModel(
    nameEn: 'Meteor 9',
    nameBn: 'মেটিওর ৯',
    fromEn: 'Uttara',
    fromBn: 'উত্তরা',
    toEn: 'Elephant Road',
    toBn: 'এলিফ্যান্ট রোড',
    fare: 32,
    stoppagesEn: [
      'Uttara',
      'Savar',
      'Banani Road',
      'Motijheel',
      'Elephant Road',
    ],
    stoppagesBn: [
      'উত্তরা',
      'সাভার',
      'বনানী রোড',
      'মতিঝিল',
      'এলিফ্যান্ট রোড',
    ],
  ),
  BusModel(
    nameEn: 'Basumoti 10',
    nameBn: 'বাসুমতি ১০',
    fromEn: 'Gulshan 1',
    fromBn: 'গুলশান ১',
    toEn: 'Mirpur 2',
    toBn: 'মিরপুর ২',
    fare: 18,
    stoppagesEn: [
      'Gulshan 1',
      'Savar Bazar',
      'Dhanmondi 27',
      'Mirpur 11',
      'Mirpur 2',
    ],
    stoppagesBn: [
      'গুলশান ১',
      'সাভার বাজার',
      'ধানমন্ডি ২৭',
      'মিরপুর ১১',
      'মিরপুর ২',
    ],
  ),
  BusModel(
    nameEn: 'Shikor 11',
    nameBn: 'শিকর ১১',
    fromEn: 'Banani',
    fromBn: 'বনানী',
    toEn: 'Farmgate',
    toBn: 'ফার্মগেট',
    fare: 24,
    stoppagesEn: ['Banani', 'Mohakhali', 'Farmgate'],
    stoppagesBn: ['বনানী', 'মহাখালী', 'ফার্মগেট'],
  ),
  BusModel(
    nameEn: 'Basumoti 12',
    nameBn: 'বাসুমতি ১২',
    fromEn: 'Dhanmondi',
    fromBn: 'ধানমন্ডি',
    toEn: 'Kawran Bazar',
    toBn: 'কাওরান বাজার',
    fare: 28,
    stoppagesEn: [
      'Dhanmondi',
      'Panthapath',
      'Kawran Bazar',
    ],
    stoppagesBn: ['ধানমন্ডি', 'পান্থপথ', 'কাওরান বাজার'],
  ),
  BusModel(
    nameEn: 'Diamond 13',
    nameBn: 'ডায়মন্ড ১৩',
    fromEn: 'Mirpur 1',
    fromBn: 'মিরপুর ১',
    toEn: 'Motijheel',
    toBn: 'মতিঝিল',
    fare: 35,
    stoppagesEn: ['Mirpur 1', 'Uttara', 'Motijheel'],
    stoppagesBn: ['মিরপুর ১', 'উত্তরা', 'মতিঝিল'],
  ),
  BusModel(
    nameEn: 'GreenLine 14',
    nameBn: 'গ্রিনলাইন ১৪',
    fromEn: 'Uttara',
    fromBn: 'উত্তরা',
    toEn: 'Banani',
    toBn: 'বনানী',
    fare: 22,
    stoppagesEn: ['Uttara', 'Gulshan', 'Banani'],
    stoppagesBn: ['উত্তরা', 'গুলশান', 'বনানী'],
  ),
  BusModel(
    nameEn: 'Bikalpa 15',
    nameBn: 'বিকল্প ১৫',
    fromEn: 'Farmgate',
    fromBn: 'ফার্মগেট',
    toEn: 'Malibagh',
    toBn: 'মালিবাগ',
    fare: 26,
    stoppagesEn: ['Farmgate', 'Mohakhali', 'Malibagh'],
    stoppagesBn: ['ফার্মগেট', 'মহাখালী', 'মালিবাগ'],
  ),
  BusModel(
    nameEn: 'Sunrise 16',
    nameBn: 'সানরাইজ ১৬',
    fromEn: 'Mirpur 2',
    fromBn: 'মিরপুর ২',
    toEn: 'Shantinagar',
    toBn: 'শান্তিনগর',
    fare: 30,
    stoppagesEn: ['Mirpur 2', 'Motijheel', 'Shantinagar'],
    stoppagesBn: ['মিরপুর ২', 'মতিঝিল', 'শান্তিনগর'],
  ),
  BusModel(
    nameEn: 'GreenLine 17',
    nameBn: 'গ্রিনলাইন ১৭',
    fromEn: 'Mirpur 5',
    fromBn: 'মিরপুর ৫',
    toEn: 'Panthapath',
    toBn: 'পান্থপথ',
    fare: 33,
    stoppagesEn: ['Mirpur 5', 'Dhanmondi', 'Panthapath'],
    stoppagesBn: ['মিরপুর ৫', 'ধানমন্ডি', 'পান্থপথ'],
  ),
  BusModel(
    nameEn: 'Meteor 18',
    nameBn: 'মেটিওর ১৮',
    fromEn: 'Gulshan 2',
    fromBn: 'গুলশান ২',
    toEn: 'Elephant Road',
    toBn: 'এলিফ্যান্ট রোড',
    fare: 40,
    stoppagesEn: [
      'Gulshan 2',
      'Motijheel',
      'Elephant Road',
    ],
    stoppagesBn: ['গুলশান ২', 'মতিঝিল', 'এলিফ্যান্ট রোড'],
  ),
  BusModel(
    nameEn: 'Basumoti 19',
    nameBn: 'বাসুমতি ১৯',
    fromEn: 'Dhanmondi 15',
    fromBn: 'ধানমন্ডি ১৫',
    toEn: 'Mirpur 10',
    toBn: 'মিরপুর ১০',
    fare: 29,
    stoppagesEn: ['Dhanmondi 15', 'Farmgate', 'Mirpur 10'],
    stoppagesBn: ['ধানমন্ডি ১৫', 'ফার্মগেট', 'মিরপুর ১০'],
  ),
  BusModel(
    nameEn: 'Shikor 20',
    nameBn: 'শিকর ২০',
    fromEn: 'Banani',
    fromBn: 'বনানী',
    toEn: 'Malibagh',
    toBn: 'মালিবাগ',
    fare: 27,
    stoppagesEn: ['Banani', 'Motijheel', 'Malibagh'],
    stoppagesBn: ['বনানী', 'মতিঝিল', 'মালিবাগ'],
  ),

  // --- বাস ২১ - ৪০ ---
  BusModel(
    nameEn: 'Agradut 21',
    nameBn: 'অগ্রদূত ২১',
    fromEn: 'Mirpur 14',
    fromBn: 'মিরপুর ১৪',
    toEn: 'Sadarghat',
    toBn: 'সদরঘাট',
    fare: 45,
    stoppagesEn: [
      'Mirpur 14',
      'Agargaon',
      'Farmgate',
      'Press Club',
      'Sadarghat',
    ],
    stoppagesBn: [
      'মিরপুর ১৪',
      'আগারগাঁও',
      'ফার্মগেট',
      'প্রেস ক্লাব',
      'সদরঘাট',
    ],
  ),
  BusModel(
    nameEn: 'Raida 22',
    nameBn: 'রাইদা ২২',
    fromEn: 'Uttara (Airport)',
    fromBn: 'উত্তরা (এয়ারপোর্ট)',
    toEn: 'Mohammadpur',
    toBn: 'মোহাম্মদপুর',
    fare: 40,
    stoppagesEn: [
      'Airport',
      'Banani',
      'Mohakhali',
      'Tejgaon',
      'Mohammadpur',
    ],
    stoppagesBn: [
      'এয়ারপোর্ট',
      'বনানী',
      'মহাখালী',
      'তেজগাঁও',
      'মোহাম্মদপুর',
    ],
  ),
  BusModel(
    nameEn: 'Salsabil 23',
    nameBn: 'সালসাবিল ২৩',
    fromEn: 'Jatrabari',
    fromBn: 'যাত্রাবাড়ী',
    toEn: 'Gazipur',
    toBn: 'গাজীপুর',
    fare: 60,
    stoppagesEn: [
      'Jatrabari',
      'Gulistan',
      'Mogbazar',
      'Mohakhali',
      'Uttara',
      'Gazipur',
    ],
    stoppagesBn: [
      'যাত্রাবাড়ী',
      'গুলিস্তান',
      'মগবাজার',
      'মহাখালী',
      'উত্তরা',
      'গাজীপুর',
    ],
  ),
  BusModel(
    nameEn: 'Transilva 24',
    nameBn: 'ট্রান্সসিলভা ২৪',
    fromEn: 'Mirpur 1',
    fromBn: 'মিরপুর ১',
    toEn: 'Motijheel',
    toBn: 'মতিঝিল',
    fare: 30,
    stoppagesEn: [
      'Mirpur 1',
      'Shyamoli',
      'Asad Gate',
      'Science Lab',
      'Shahbag',
      'Motijheel',
    ],
    stoppagesBn: [
      'মিরপুর ১',
      'শ্যামলী',
      'আসাদ গেট',
      'সায়েন্স ল্যাব',
      'শাহবাগ',
      'মতিঝিল',
    ],
  ),
  BusModel(
    nameEn: 'Itihas 25',
    nameBn: 'ইতিহাস ২৫',
    fromEn: 'Gabtoli',
    fromBn: 'গাবতলী',
    toEn: 'Badda Link Road',
    toBn: 'বাড্ডা লিংক রোড',
    fare: 35,
    stoppagesEn: [
      'Gabtoli',
      'Shyamoli',
      'Agargaon',
      'Nabisco',
      'Gulshan 1',
      'Badda',
    ],
    stoppagesBn: [
      'গাবতলী',
      'শ্যামলী',
      'আগারগাঁও',
      'নাবিস্কো',
      'গুলশান ১',
      'বাড্ডা',
    ],
  ),
  BusModel(
    nameEn: 'Safety 26',
    nameBn: 'সেফটি ২৬',
    fromEn: 'Mohammadpur',
    fromBn: 'মোহাম্মদপুর',
    toEn: 'Rampura',
    toBn: 'রামপুরা',
    fare: 25,
    stoppagesEn: [
      'Mohammadpur',
      'Science Lab',
      'Banglamotor',
      'Mouchak',
      'Rampura',
    ],
    stoppagesBn: [
      'মোহাম্মদপুর',
      'সায়েন্স ল্যাব',
      'বাংলামোটর',
      'মৌচাক',
      'রামপুরা',
    ],
  ),
  BusModel(
    nameEn: 'Akash 27',
    nameBn: 'আকাশ ২৭',
    fromEn: 'Dhanmondi 15',
    fromBn: 'ধানমন্ডি ১৫',
    toEn: 'Abdullahpur',
    toBn: 'আব্দুল্লাহপুর',
    fare: 50,
    stoppagesEn: [
      'Dhanmondi 15',
      'Farmgate',
      'Mohakhali',
      'Banani',
      'Uttara',
      'Abdullahpur',
    ],
    stoppagesBn: [
      'ধানমন্ডি ১৫',
      'ফার্মগেট',
      'মহাখালী',
      'বনানী',
      'উত্তরা',
      'আব্দুল্লাহপুর',
    ],
  ),
  BusModel(
    nameEn: 'Achim 28',
    nameBn: 'অছিম ২৮',
    fromEn: 'New Market',
    fromBn: 'নিউ মার্কেট',
    toEn: 'Kuril',
    toBn: 'কুড়িল',
    fare: 35,
    stoppagesEn: [
      'New Market',
      'Shahbag',
      'Kakrail',
      'Malibagh',
      'Badda',
      'Kuril',
    ],
    stoppagesBn: [
      'নিউ মার্কেট',
      'শাহবাগ',
      'কাকরাইল',
      'মালিবাগ',
      'বাড্ডা',
      'কুড়িল',
    ],
  ),
  BusModel(
    nameEn: 'Labbayek 29',
    nameBn: 'লাব্বায়েক ২৯',
    fromEn: 'Savar',
    fromBn: 'সাভার',
    toEn: 'Jatrabari',
    toBn: 'যাত্রাবাড়ী',
    fare: 70,
    stoppagesEn: [
      'Savar',
      'Gabtoli',
      'Asad Gate',
      'Shahbag',
      'Gulistan',
      'Jatrabari',
    ],
    stoppagesBn: [
      'সাভার',
      'গাবতলী',
      'আসাদ গেট',
      'শাহবাগ',
      'গুলিস্তান',
      'যাত্রাবাড়ী',
    ],
  ),
  BusModel(
    nameEn: 'Alif 30',
    nameBn: 'আলিফ ৩০',
    fromEn: 'Mirpur 10',
    fromBn: 'মিরপুর ১০',
    toEn: 'Kamalapur',
    toBn: 'কমলাপুর',
    fare: 30,
    stoppagesEn: [
      'Mirpur 10',
      'Kazipara',
      'Farmgate',
      'Mogbazar',
      'Kamalapur',
    ],
    stoppagesBn: [
      'মিরপুর ১০',
      'কাজীপাড়া',
      'ফার্মগেট',
      'মগবাজার',
      'কমলাপুর',
    ],
  ),
  BusModel(
    nameEn: 'Ayat 31',
    nameBn: 'আয়াত ৩১',
    fromEn: 'Dhamrai',
    fromBn: 'ধামরাই',
    toEn: 'Gulistan',
    toBn: 'গুলিস্তান',
    fare: 80,
    stoppagesEn: [
      'Dhamrai',
      'Savar',
      'Gabtoli',
      'Farmgate',
      'Gulistan',
    ],
    stoppagesBn: [
      'ধামরাই',
      'সাভার',
      'গাবতলী',
      'ফার্মগেট',
      'গুলিস্তান',
    ],
  ),
  BusModel(
    nameEn: 'Bikash 32',
    nameBn: 'বিকাশ ৩২',
    fromEn: 'Narayanganj',
    fromBn: 'নারায়ণগঞ্জ',
    toEn: 'Abdullahpur',
    toBn: 'আব্দুল্লাহপুর',
    fare: 65,
    stoppagesEn: [
      'Narayanganj',
      'Jatrabari',
      'Gulistan',
      'Mohakhali',
      'Uttara',
      'Abdullahpur',
    ],
    stoppagesBn: [
      'নারায়ণগঞ্জ',
      'যাত্রাবাড়ী',
      'গুলিস্তান',
      'মহাখালী',
      'উত্তরা',
      'আব্দুল্লাহপুর',
    ],
  ),
  BusModel(
    nameEn: 'Welcome 33',
    nameBn: 'ওয়েলকাম ৩৩',
    fromEn: 'Keraniganj',
    fromBn: 'কেরানীগঞ্জ',
    toEn: 'Uttara',
    toBn: 'উত্তরা',
    fare: 55,
    stoppagesEn: [
      'Keraniganj',
      'New Market',
      'Farmgate',
      'Banani',
      'Uttara',
    ],
    stoppagesBn: [
      'কেরানীগঞ্জ',
      'নিউ মার্কেট',
      'ফার্মগেট',
      'বনানী',
      'উত্তরা',
    ],
  ),
  BusModel(
    nameEn: 'BRTC 34',
    nameBn: 'বিআরটিসি ৩৪',
    fromEn: 'Motijheel',
    fromBn: 'মতিঝিল',
    toEn: 'Abdullahpur',
    toBn: 'আব্দুল্লাহপুর',
    fare: 40,
    stoppagesEn: [
      'Motijheel',
      'Shahbag',
      'Farmgate',
      'Mohakhali',
      'Airport',
      'Abdullahpur',
    ],
    stoppagesBn: [
      'মতিঝিল',
      'শাহবাগ',
      'ফার্মগেট',
      'মহাখালী',
      'এয়ারপোর্ট',
      'আব্দুল্লাহপুর',
    ],
  ),
  BusModel(
    nameEn: 'Rajanigandha 35',
    nameBn: 'রজনীগন্ধা ৩৫',
    fromEn: 'Chittagong Road',
    fromBn: 'চিটাগং রোড',
    toEn: 'Mirpur 10',
    toBn: 'মিরপুর ১০',
    fare: 50,
    stoppagesEn: [
      'Chittagong Road',
      'Jatrabari',
      'Gulistan',
      'Farmgate',
      'Mirpur 10',
    ],
    stoppagesBn: [
      'চিটাগং রোড',
      'যাত্রাবাড়ী',
      'গুলিস্তান',
      'ফার্মগেট',
      'মিরপুর ১০',
    ],
  ),
  BusModel(
    nameEn: 'Taqwa 36',
    nameBn: 'তাকওয়া ৩৬',
    fromEn: 'Signboard',
    fromBn: 'সাইন বোর্ড',
    toEn: 'Mirpur 12',
    toBn: 'মিরপুর ১২',
    fare: 50,
    stoppagesEn: [
      'Signboard',
      'Kakrail',
      'Farmgate',
      'Agargaon',
      'Mirpur 12',
    ],
    stoppagesBn: [
      'সাইন বোর্ড',
      'কাকরাইল',
      'ফার্মগেট',
      'আগারগাঁও',
      'মিরপুর ১২',
    ],
  ),
  BusModel(
    nameEn: 'Victor 37',
    nameBn: 'ভিক্টর ৩৭',
    fromEn: 'Sadarghat',
    fromBn: 'সদরঘাট',
    toEn: 'Kuril',
    toBn: 'কুড়িল',
    fare: 40,
    stoppagesEn: [
      'Sadarghat',
      'Gulistan',
      'Malibagh',
      'Badda',
      'Kuril',
    ],
    stoppagesBn: [
      'সদরঘাট',
      'গুলিস্তান',
      'মালিবাগ',
      'বাড্ডা',
      'কুড়িল',
    ],
  ),
  BusModel(
    nameEn: 'Trust 38',
    nameBn: 'ট্রাস্ট ৩৮',
    fromEn: 'New Market',
    fromBn: 'নিউ মার্কেট',
    toEn: 'Nadda',
    toBn: 'নদ্দা',
    fare: 30,
    stoppagesEn: [
      'New Market',
      'Science Lab',
      'Farmgate',
      'Gulshan 1',
      'Nadda',
    ],
    stoppagesBn: [
      'নিউ মার্কেট',
      'সায়েন্স ল্যাব',
      'ফার্মগেট',
      'গুলশান ১',
      'নদ্দা',
    ],
  ),
  BusModel(
    nameEn: 'Midline 39',
    nameBn: 'মিডলাইন ৩৯',
    fromEn: 'Banasree',
    fromBn: 'বনশ্রী',
    toEn: 'Motijheel',
    toBn: 'মতিঝিল',
    fare: 25,
    stoppagesEn: [
      'Banasree',
      'Rampura',
      'Malibagh',
      'Kakrail',
      'Motijheel',
    ],
    stoppagesBn: [
      'বনশ্রী',
      'রামপুরা',
      'মালিবাগ',
      'কাকরাইল',
      'মতিঝিল',
    ],
  ),
  BusModel(
    nameEn: 'Anabil 40',
    nameBn: 'অনাবিল ৪০',
    fromEn: 'Gazipur',
    fromBn: 'গাজীপুর',
    toEn: 'Narayanganj',
    toBn: 'নারায়ণগঞ্জ',
    fare: 80,
    stoppagesEn: [
      'Gazipur',
      'Uttara',
      'Mohakhali',
      'Gulistan',
      'Jatrabari',
      'Narayanganj',
    ],
    stoppagesBn: [
      'গাজীপুর',
      'উত্তরা',
      'মহাখালী',
      'গুলিস্তান',
      'যাত্রাবাড়ী',
      'নারায়ণগঞ্জ',
    ],
  ),

  // --- বাস ৪১ - ৭০+ ---
  BusModel(
    nameEn: 'Turag 41',
    nameBn: 'তুরাগ ৪১',
    fromEn: 'Tongi',
    fromBn: 'টঙ্গী',
    toEn: 'Gulistan',
    toBn: 'গুলিস্তান',
    fare: 45,
    stoppagesEn: [
      'Tongi',
      'Airport',
      'Mohakhali',
      'Farmgate',
      'Gulistan',
    ],
    stoppagesBn: [
      'টঙ্গী',
      'এয়ারপোর্ট',
      'মহাখালী',
      'ফার্মগেট',
      'গুলিস্তান',
    ],
  ),
  BusModel(
    nameEn: 'Srabon 42',
    nameBn: 'শ্রাবণ ৪২',
    fromEn: 'Mirpur 12',
    fromBn: 'মিরপুর ১২',
    toEn: 'New Market',
    toBn: 'নিউ মার্কেট',
    fare: 30,
    stoppagesEn: [
      'Mirpur 12',
      'Mirpur 10',
      'Agargaon',
      'Science Lab',
      'New Market',
    ],
    stoppagesBn: [
      'মিরপুর ১২',
      'মিরপুর ১০',
      'আগারগাঁও',
      'সায়েন্স ল্যাব',
      'নিউ মার্কেট',
    ],
  ),
  BusModel(
    nameEn: 'Himachol 43',
    nameBn: 'হিমাচল ৪৩',
    fromEn: 'Abdullahpur',
    fromBn: 'আব্দুল্লাহপুর',
    toEn: 'Sadarghat',
    toBn: 'সদরঘাট',
    fare: 55,
    stoppagesEn: [
      'Abdullahpur',
      'Uttara',
      'Banani',
      'Farmgate',
      'Press Club',
      'Sadarghat',
    ],
    stoppagesBn: [
      'আব্দুল্লাহপুর',
      'উত্তরা',
      'বনানী',
      'ফার্মগেট',
      'প্রেস ক্লাব',
      'সদরঘাট',
    ],
  ),
  BusModel(
    nameEn: 'Bihongo 44',
    nameBn: 'বিহঙ্গ ৪৪',
    fromEn: 'Gabtoli',
    fromBn: 'গাবতলী',
    toEn: 'Gulshan 2',
    toBn: 'গুলশান ২',
    fare: 35,
    stoppagesEn: [
      'Gabtoli',
      'Shyamoli',
      'Mohakhali',
      'Gulshan 1',
      'Gulshan 2',
    ],
    stoppagesBn: [
      'গাবতলী',
      'শ্যামলী',
      'মহাখালী',
      'গুলশান ১',
      'গুলশান ২',
    ],
  ),
  BusModel(
    nameEn: 'Falguni 45',
    nameBn: 'ফাল্গুনী ৪৫',
    fromEn: 'Mohammadpur',
    fromBn: 'মোহাম্মদপুর',
    toEn: 'Badda',
    toBn: 'বাড্ডা',
    fare: 25,
    stoppagesEn: [
      'Mohammadpur',
      'Farmgate',
      'Nabisco',
      'Gulshan 1',
      'Badda',
    ],
    stoppagesBn: [
      'মোহাম্মদপুর',
      'ফার্মগেট',
      'নাবিস্কো',
      'গুলশান ১',
      'বাড্ডা',
    ],
  ),
  BusModel(
    nameEn: 'VIP 27 (46)',
    nameBn: 'ভিআইপি ২৭ (৪৬)',
    fromEn: 'Uttara',
    fromBn: 'উত্তরা',
    toEn: 'Motijheel',
    toBn: 'মতিঝিল',
    fare: 50,
    stoppagesEn: [
      'Uttara',
      'Banani',
      'Shahbag',
      'Motijheel',
    ],
    stoppagesBn: ['উত্তরা', 'বনানী', 'শাহবাগ', 'মতিঝিল'],
  ),
  BusModel(
    nameEn: 'Projapoti 47',
    nameBn: 'প্রজাপতি ৪৭',
    fromEn: 'Gabtoli',
    fromBn: 'গাবতলী',
    toEn: 'Abdullahpur',
    toBn: 'আব্দুল্লাহপুর',
    fare: 40,
    stoppagesEn: [
      'Gabtoli',
      'Mirpur 1',
      'Mirpur 10',
      'Kalshi',
      'Uttara',
      'Abdullahpur',
    ],
    stoppagesBn: [
      'গাবতলী',
      'মিরপুর ১',
      'মিরপুর ১০',
      'কালশী',
      'উত্তরা',
      'আব্দুল্লাহপুর',
    ],
  ),
  BusModel(
    nameEn: 'Desh Bangla 48',
    nameBn: 'দেশ বাংলা ৪৮',
    fromEn: 'Narayanganj',
    fromBn: 'নারায়ণগঞ্জ',
    toEn: 'Tongi',
    toBn: 'টঙ্গী',
    fare: 70,
    stoppagesEn: [
      'Narayanganj',
      'Gulistan',
      'Mohakhali',
      'Uttara',
      'Tongi',
    ],
    stoppagesBn: [
      'নারায়ণগঞ্জ',
      'গুলিস্তান',
      'মহাখালী',
      'উত্তরা',
      'টঙ্গী',
    ],
  ),
  BusModel(
    nameEn: 'Meghna 49',
    nameBn: 'মেঘনা ৪৯',
    fromEn: 'Banasree',
    fromBn: 'বনশ্রী',
    toEn: 'Dhanmondi',
    toBn: 'ধানমন্ডি',
    fare: 35,
    stoppagesEn: [
      'Banasree',
      'Rampura',
      'Mogbazar',
      'Science Lab',
      'Dhanmondi',
    ],
    stoppagesBn: [
      'বনশ্রী',
      'রামপুরা',
      'মগবাজার',
      'সায়েন্স ল্যাব',
      'ধানমন্ডি',
    ],
  ),
  BusModel(
    nameEn: 'Asmani 50',
    nameBn: 'আসমানে ৫০',
    fromEn: 'Mirpur 14',
    fromBn: 'মিরপুর ১৪',
    toEn: 'Kamalapur',
    toBn: 'কমলাপুর',
    fare: 30,
    stoppagesEn: [
      'Mirpur 14',
      'Agargaon',
      'Farmgate',
      'Malibagh',
      'Kamalapur',
    ],
    stoppagesBn: [
      'মিরপুর ১৪',
      'আগারগাঁও',
      'ফার্মগেট',
      'মালিবাগ',
      'কমলাপুর',
    ],
  ),
  BusModel(
    nameEn: 'Boishakhi 51',
    nameBn: 'বৈশাখী ৫১',
    fromEn: 'Savar',
    fromBn: 'সাভার',
    toEn: 'New Market',
    toBn: 'নিউ মার্কেট',
    fare: 50,
    stoppagesEn: [
      'Savar',
      'Gabtoli',
      'Asad Gate',
      'New Market',
    ],
    stoppagesBn: [
      'সাভার',
      'গাবতলী',
      'আসাদ গেট',
      'নিউ মার্কেট',
    ],
  ),
  BusModel(
    nameEn: 'Shanti 52',
    nameBn: 'শান্তি ৫২',
    fromEn: 'Jatrabari',
    fromBn: 'যাত্রাবাড়ী',
    toEn: 'Mirpur 1',
    toBn: 'মিরপুর ১',
    fare: 45,
    stoppagesEn: [
      'Jatrabari',
      'Gulistan',
      'Farmgate',
      'Shyamoli',
      'Mirpur 1',
    ],
    stoppagesBn: [
      'যাত্রাবাড়ী',
      'গুলিস্তান',
      'ফার্মগেট',
      'শ্যামলী',
      'মিরপুর ১',
    ],
  ),
  BusModel(
    nameEn: 'Everest 53',
    nameBn: 'এভারেস্ট ৫৩',
    fromEn: 'Mohakhali',
    fromBn: 'মহাখালী',
    toEn: 'Sadarghat',
    toBn: 'সদরঘাট',
    fare: 35,
    stoppagesEn: [
      'Mohakhali',
      'Farmgate',
      'Shahbag',
      'Gulistan',
      'Sadarghat',
    ],
    stoppagesBn: [
      'মহাখালী',
      'ফার্মগেট',
      'শাহবাগ',
      'গুলিস্তান',
      'সদরঘাট',
    ],
  ),
  BusModel(
    nameEn: 'Arambagh 54',
    nameBn: 'আরামবাগ ৫৪',
    fromEn: 'Arambagh',
    fromBn: 'আরামবাগ',
    toEn: 'Uttara',
    toBn: 'উত্তরা',
    fare: 40,
    stoppagesEn: [
      'Arambagh',
      'Kakrail',
      'Mohakhali',
      'Banani',
      'Uttara',
    ],
    stoppagesBn: [
      'আরামবাগ',
      'কাকরাইল',
      'মহাখালী',
      'বনানী',
      'উত্তরা',
    ],
  ),
  BusModel(
    nameEn: 'Pallabi 55',
    nameBn: 'পল্লবী ৫৫',
    fromEn: 'Pallabi',
    fromBn: 'পল্লবী',
    toEn: 'Motijheel',
    toBn: 'মতিঝিল',
    fare: 30,
    stoppagesEn: [
      'Pallabi',
      'Mirpur 10',
      'Farmgate',
      'Paltan',
      'Motijheel',
    ],
    stoppagesBn: [
      'পল্লবী',
      'মিরপুর ১০',
      'ফার্মগেট',
      'পল্টন',
      'মতিঝিল',
    ],
  ),
  BusModel(
    nameEn: 'BRTC 56',
    nameBn: 'বিআরটিসি ৫৬',
    fromEn: 'Gabtoli',
    fromBn: 'গাবতলী',
    toEn: 'Motijheel',
    toBn: 'মতিঝিল',
    fare: 30,
    stoppagesEn: [
      'Gabtoli',
      'Asad Gate',
      'Science Lab',
      'Shahbag',
      'Motijheel',
    ],
    stoppagesBn: [
      'গাবতলী',
      'আসাদ গেট',
      'সায়েন্স ল্যাব',
      'শাহবাগ',
      'মতিঝিল',
    ],
  ),
  BusModel(
    nameEn: 'Shadhin 57',
    nameBn: 'স্বাধীন ৫৭',
    fromEn: 'Mirpur 1',
    fromBn: 'মিরপুর ১',
    toEn: 'Gulshan 1',
    toBn: 'গুলশান ১',
    fare: 25,
    stoppagesEn: [
      'Mirpur 1',
      'Agargaon',
      'Mohakhali',
      'Gulshan 1',
    ],
    stoppagesBn: [
      'মিরপুর ১',
      'আগারগাঁও',
      'মহাখালী',
      'গুলশান ১',
    ],
  ),
  BusModel(
    nameEn: 'Malancha 58',
    nameBn: 'মালঞ্চ ৫৮',
    fromEn: 'Farmgate',
    fromBn: 'ফার্মগেট',
    toEn: 'Narayanganj',
    toBn: 'নারায়ণগঞ্জ',
    fare: 45,
    stoppagesEn: [
      'Farmgate',
      'Shahbag',
      'Gulistan',
      'Jatrabari',
      'Narayanganj',
    ],
    stoppagesBn: [
      'ফার্মগেট',
      'শাহবাগ',
      'গুলিস্তান',
      'যাত্রাবাড়ী',
      'নারায়ণগঞ্জ',
    ],
  ),
  BusModel(
    nameEn: 'Himaloy 59',
    nameBn: 'হিমালয় ৫৯',
    fromEn: 'Savar',
    fromBn: 'সাভার',
    toEn: 'Motijheel',
    toBn: 'মতিঝিল',
    fare: 60,
    stoppagesEn: [
      'Savar',
      'Gabtoli',
      'Farmgate',
      'Paltan',
      'Motijheel',
    ],
    stoppagesBn: [
      'সাভার',
      'গাবতলী',
      'ফার্মগেট',
      'পল্টন',
      'মতিঝিল',
    ],
  ),
  BusModel(
    nameEn: 'Thikana 60',
    nameBn: 'ঠিকানা ৬০',
    fromEn: 'Mirpur 10',
    fromBn: 'মিরপুর ১০',
    toEn: 'Badda',
    toBn: 'বাড্ডা',
    fare: 25,
    stoppagesEn: [
      'Mirpur 10',
      'Mohakhali',
      'Gulshan 1',
      'Badda',
    ],
    stoppagesBn: [
      'মিরপুর ১০',
      'মহাখালী',
      'গুলশান ১',
      'বাড্ডা',
    ],
  ),
  BusModel(
    nameEn: 'Balaka 61',
    nameBn: 'বলাকা ৬১',
    fromEn: 'Sadarghat',
    fromBn: 'সদরঘাট',
    toEn: 'Gazipur',
    toBn: 'গাজীপুর',
    fare: 65,
    stoppagesEn: [
      'Sadarghat',
      'Gulistan',
      'Mohakhali',
      'Uttara',
      'Gazipur',
    ],
    stoppagesBn: [
      'সদরঘাট',
      'গুলিস্তান',
      'মহাখালী',
      'উত্তরা',
      'গাজীপুর',
    ],
  ),
  BusModel(
    nameEn: 'New Vision 62',
    nameBn: 'নিউ ভিশন ৬২',
    fromEn: 'Motijheel',
    fromBn: 'মতিঝিল',
    toEn: 'Mirpur 14',
    toBn: 'মিরপুর ১৪',
    fare: 35,
    stoppagesEn: [
      'Motijheel',
      'Farmgate',
      'Agargaon',
      'Mirpur 14',
    ],
    stoppagesBn: [
      'মতিঝিল',
      'ফার্মগেট',
      'আগারগাঁও',
      'মিরপুর ১৪',
    ],
  ),
  BusModel(
    nameEn: 'Prochesta 63',
    nameBn: 'প্রচেষ্টা ৬৩',
    fromEn: 'Mohammadpur',
    fromBn: 'মোহাম্মদপুর',
    toEn: 'Natun Bazar',
    toBn: 'নতুন বাজার',
    fare: 30,
    stoppagesEn: [
      'Mohammadpur',
      'Asad Gate',
      'Mohakhali',
      'Gulshan 1',
      'Natun Bazar',
    ],
    stoppagesBn: [
      'মোহাম্মদপুর',
      'আসাদ গেট',
      'মহাখালী',
      'গুলশান ১',
      'নতুন বাজার',
    ],
  ),
  BusModel(
    nameEn: 'Jamuna 64',
    nameBn: 'যমুনা ৬৪',
    fromEn: 'Uttara',
    fromBn: 'উত্তরা',
    toEn: 'Kamalapur',
    toBn: 'কমলাপুর',
    fare: 40,
    stoppagesEn: [
      'Uttara',
      'Mohakhali',
      'Mogbazar',
      'Kamalapur',
    ],
    stoppagesBn: [
      'উত্তরা',
      'মহাখালী',
      'মগবাজার',
      'কমলাপুর',
    ],
  ),
  BusModel(
    nameEn: 'Bondhon 65',
    nameBn: 'বন্ধন ৬৫',
    fromEn: 'New Market',
    fromBn: 'নিউ মার্কেট',
    toEn: 'Banasree',
    toBn: 'বনশ্রী',
    fare: 30,
    stoppagesEn: [
      'New Market',
      'Shahbag',
      'Malibagh',
      'Rampura',
      'Banasree',
    ],
    stoppagesBn: [
      'নিউ মার্কেট',
      'শাহবাগ',
      'মালিবাগ',
      'রামপুরা',
      'বনশ্রী',
    ],
  ),
  BusModel(
    nameEn: 'Paristan 66',
    nameBn: 'পারিস্তান ৬৬',
    fromEn: 'Mirpur 12',
    fromBn: 'মিরপুর ১২',
    toEn: 'Motijheel',
    toBn: 'মতিঝিল',
    fare: 35,
    stoppagesEn: [
      'Mirpur 12',
      'Mirpur 10',
      'Farmgate',
      'Paltan',
      'Motijheel',
    ],
    stoppagesBn: [
      'মিরপুর ১২',
      'মিরপুর ১০',
      'ফার্মগেট',
      'পল্টন',
      'মতিঝিল',
    ],
  ),
  BusModel(
    nameEn: 'One Bus 67',
    nameBn: 'ওয়ান বাস ৬৭',
    fromEn: 'Gabtoli',
    fromBn: 'গাবতলী',
    toEn: 'Jatrabari',
    toBn: 'যাত্রাবাড়ী',
    fare: 45,
    stoppagesEn: [
      'Gabtoli',
      'Asad Gate',
      'Shahbag',
      'Gulistan',
      'Jatrabari',
    ],
    stoppagesBn: [
      'গাবতলী',
      'আসাদ গেট',
      'শাহবাগ',
      'গুলিস্তান',
      'যাত্রাবাড়ী',
    ],
  ),
  BusModel(
    nameEn: 'Bahon 68',
    nameBn: 'বাহন ৬৮',
    fromEn: 'Pallabi',
    fromBn: 'পল্লবী',
    toEn: 'Sadarghat',
    toBn: 'সদরঘাট',
    fare: 40,
    stoppagesEn: [
      'Pallabi',
      'Mirpur 10',
      'Farmgate',
      'Gulistan',
      'Sadarghat',
    ],
    stoppagesBn: [
      'পল্লবী',
      'মিরপুর ১০',
      'ফার্মগেট',
      'গুলিস্তান',
      'সদরঘাট',
    ],
  ),
  BusModel(
    nameEn: 'Dhaka Metro 69',
    nameBn: 'ঢাকা মেট্রো ৬৯',
    fromEn: 'Dhanmondi',
    fromBn: 'ধানমন্ডি',
    toEn: 'Uttara',
    toBn: 'উত্তরা',
    fare: 45,
    stoppagesEn: [
      'Dhanmondi',
      'Asad Gate',
      'Mohakhali',
      'Banani',
      'Uttara',
    ],
    stoppagesBn: [
      'ধানমন্ডি',
      'আসাদ গেট',
      'মহাখালী',
      'বনানী',
      'উত্তরা',
    ],
  ),
  BusModel(
    nameEn: 'Airport 70',
    nameBn: 'এয়ারপোর্ট ৭০',
    fromEn: 'Airport',
    fromBn: 'এয়ারপোর্ট',
    toEn: 'Motijheel',
    toBn: 'মতিঝিল',
    fare: 40,
    stoppagesEn: [
      'Airport',
      'Mohakhali',
      'Farmgate',
      'Shahbag',
      'Motijheel',
    ],
    stoppagesBn: [
      'এয়ারপোর্ট',
      'মহাখালী',
      'ফার্মগেট',
      'শাহবাগ',
      'মতিঝিল',
    ],
  ),
];
