// data/bus_data.dart
import '../models/bus_model.dart';

final List<BusModel> busList = [
  BusModel(
    nameEn: 'Shikor 1',
    nameBn: 'শিকর ১',
    fromEn: 'Banani',
    fromBn: 'বনানী',
    toEn: 'Kawran Bazar',
    toBn: 'কাওরান বাজার',
    fare: 21,
    stoppagesEn: ['Banani', 'Mohakhali', 'Kawran Bazar'],
    stoppagesBn: ['বনানী', 'মহাখালী', 'কাওরান বাজার'],
  ),
  BusModel(
    nameEn: 'Basumoti 2',
    nameBn: 'বাসুমতি ২',
    fromEn: 'Farmgate Bypass',
    fromBn: 'ফার্মগেট বাইপাস',
    toEn: 'Malibagh',
    toBn: 'মালিবাগ',
    fare: 22,
    stoppagesEn: ['Farmgate', 'Mogbazar', 'Malibagh'],
    stoppagesBn: ['ফার্মগেট', 'মগবাজার', 'মালিবাগ'],
  ),

  // ... আপনার অন্যান্য বাসগুলো এখানে থাকবে ... (আমি শুধু ২টি দেখাচ্ছি)
  BusModel(
    nameEn: 'Agradut 21',
    nameBn: 'অগ্রদূত ২১',
    fromEn: 'Mirpur 14',
    fromBn: 'মিরপুর ১৪',
    toEn: 'Sadarghat',
    toBn: 'সদরঘাট',
    fare: 45,
    stoppagesEn: [
      'Mirpur 14',
      'Agargaon',
      'Farmgate',
      'Press Club',
      'Sadarghat',
    ],
    stoppagesBn: [
      'মিরপুর ১৪',
      'আগারগাঁও',
      'ফার্মগেট',
      'প্রেস ক্লাব',
      'সদরঘাট',
    ],
  ),
  BusModel(
    nameEn: 'Raida 22',
    nameBn: 'রাইদা ২২',
    fromEn: 'Uttara (Airport)',
    fromBn: 'উত্তরা (এয়ারপোর্ট)',
    toEn: 'Mohammadpur',
    toBn: 'মোহাম্মদপুর',
    fare: 40,
    stoppagesEn: [
      'Airport',
      'Banani',
      'Mohakhali',
      'Tejgaon',
      'Mohammadpur',
    ],
    stoppagesBn: [
      'এয়ারপোর্ট',
      'বনানী',
      'মহাখালী',
      'তেজগাঁও',
      'মোহাম্মদপুর',
    ],
  ),
  BusModel(
    nameEn: 'Salsabil 23',
    nameBn: 'সালসাবিল ২৩',
    fromEn: 'Jatrabari',
    fromBn: 'যাত্রাবাড়ী',
    toEn: 'Gazipur',
    toBn: 'গাজীপুর',
    fare: 60,
    stoppagesEn: [
      'Jatrabari',
      'Gulistan',
      'Mogbazar',
      'Mohakhali',
      'Uttara',
      'Gazipur',
    ],
    stoppagesBn: [
      'যাত্রাবাড়ী',
      'গুলিস্তান',
      'মগবাজার',
      'মহাখালী',
      'উত্তরা',
      'গাজীপুর',
    ],
  ),
  BusModel(
    nameEn: 'Transilva 24',
    nameBn: 'ট্রান্সসিলভা ২৪',
    fromEn: 'Mirpur 1',
    fromBn: 'মিরপুর ১',
    toEn: 'Motijheel',
    toBn: 'মতিঝিল',
    fare: 30,
    stoppagesEn: [
      'Mirpur 1',
      'Shyamoli',
      'Asad Gate',
      'Science Lab',
      'Shahbag',
      'Motijheel',
    ],
    stoppagesBn: [
      'মিরপুর ১',
      'শ্যামলী',
      'আসাদ গেট',
      'সায়েন্স ল্যাব',
      'শাহবাগ',
      'মতিঝিল',
    ],
  ),
  BusModel(
    nameEn: 'Itihas 25',
    nameBn: 'ইতিহাস ২৫',
    fromEn: 'Gabtoli',
    fromBn: 'গাবতলী',
    toEn: 'Badda Link Road',
    toBn: 'বাড্ডা লিংক রোড',
    fare: 35,
    stoppagesEn: [
      'Gabtoli',
      'Shyamoli',
      'Agargaon',
      'Nabisco',
      'Gulshan 1',
      'Badda',
    ],
    stoppagesBn: [
      'গাবতলী',
      'শ্যামলী',
      'আগারগাঁও',
      'নাবিস্কো',
      'গুলশান ১',
      'বাড্ডা',
    ],
  ),
  BusModel(
    nameEn: 'Safety 26',
    nameBn: 'সেফটি ২৬',
    fromEn: 'Mohammadpur',
    fromBn: 'মোহাম্মদপুর',
    toEn: 'Rampura',
    toBn: 'রামপুরা',
    fare: 25,
    stoppagesEn: [
      'Mohammadpur',
      'Science Lab',
      'Banglamotor',
      'Mouchak',
      'Rampura',
    ],
    stoppagesBn: [
      'মোহাম্মদপুর',
      'সায়েন্স ল্যাব',
      'বাংলামোটর',
      'মৌচাক',
      'রামপুরা',
    ],
  ),
  BusModel(
    nameEn: 'Akash 27',
    nameBn: 'আকাশ ২৭',
    fromEn: 'Dhanmondi 15',
    fromBn: 'ধানমন্ডি ১৫',
    toEn: 'Abdullahpur',
    toBn: 'আব্দুল্লাহপুর',
    fare: 50,
    stoppagesEn: [
      'Dhanmondi 15',
      'Farmgate',
      'Mohakhali',
      'Banani',
      'Uttara',
      'Abdullahpur',
    ],
    stoppagesBn: [
      'ধানমন্ডি ১৫',
      'ফার্মগেট',
      'মহাখালী',
      'বনানী',
      'উত্তরা',
      'আব্দুল্লাহপুর',
    ],
  ),
  BusModel(
    nameEn: 'Achim 28',
    nameBn: 'অছিম ২৮',
    fromEn: 'New Market',
    fromBn: 'নিউ মার্কেট',
    toEn: 'Kuril',
    toBn: 'কুড়িল',
    fare: 35,
    stoppagesEn: [
      'New Market',
      'Shahbag',
      'Kakrail',
      'Malibagh',
      'Badda',
      'Kuril',
    ],
    stoppagesBn: [
      'নিউ মার্কেট',
      'শাহবাগ',
      'কাকরাইল',
      'মালিবাগ',
      'বাড্ডা',
      'কুড়িল',
    ],
  ),
  BusModel(
    nameEn: 'Labbayek 29',
    nameBn: 'লাব্বায়েক ২৯',
    fromEn: 'Savar',
    fromBn: 'সাভার',
    toEn: 'Jatrabari',
    toBn: 'যাত্রাবাড়ী',
    fare: 70,
    stoppagesEn: [
      'Savar',
      'Gabtoli',
      'Asad Gate',
      'Shahbag',
      'Gulistan',
      'Jatrabari',
    ],
    stoppagesBn: [
      'সাভার',
      'গাবতলী',
      'আসাদ গেট',
      'শাহবাগ',
      'গুলিস্তান',
      'যাত্রাবাড়ী',
    ],
  ),
  BusModel(
    nameEn: 'Alif 30',
    nameBn: 'আলিফ ৩০',
    fromEn: 'Mirpur 10',
    fromBn: 'মিরপুর ১০',
    toEn: 'Kamalapur',
    toBn: 'কমলাপুর',
    fare: 30,
    stoppagesEn: [
      'Mirpur 10',
      'Kazipara',
      'Farmgate',
      'Mogbazar',
      'Kamalapur',
    ],
    stoppagesBn: [
      'মিরপুর ১০',
      'কাজীপাড়া',
      'ফার্মগেট',
      'মগবাজার',
      'কমলাপুর',
    ],
  ),
  BusModel(
    nameEn: 'Ayat 31',
    nameBn: 'আয়াত ৩১',
    fromEn: 'Dhamrai',
    fromBn: 'ধামরাই',
    toEn: 'Gulistan',
    toBn: 'গুলিস্তান',
    fare: 80,
    stoppagesEn: [
      'Dhamrai',
      'Savar',
      'Gabtoli',
      'Farmgate',
      'Gulistan',
    ],
    stoppagesBn: [
      'ধামরাই',
      'সাভার',
      'গাবতলী',
      'ফার্মগেট',
      'গুলিস্তান',
    ],
  ),
  BusModel(
    nameEn: 'Bikash 32',
    nameBn: 'বিকাশ ৩২',
    fromEn: 'Narayanganj',
    fromBn: 'নারায়ণগঞ্জ',
    toEn: 'Abdullahpur',
    toBn: 'আব্দুল্লাহপুর',
    fare: 65,
    stoppagesEn: [
      'Narayanganj',
      'Jatrabari',
      'Gulistan',
      'Mohakhali',
      'Uttara',
      'Abdullahpur',
    ],
    stoppagesBn: [
      'নারায়ণগঞ্জ',
      'যাত্রাবাড়ী',
      'গুলিস্তান',
      'মহাখালী',
      'উত্তরা',
      'আব্দুল্লাহপুর',
    ],
  ),
  BusModel(
    nameEn: 'Welcome 33',
    nameBn: 'ওয়েলকাম ৩৩',
    fromEn: 'Keraniganj',
    fromBn: 'কেরানীগঞ্জ',
    toEn: 'Uttara',
    toBn: 'উত্তরা',
    fare: 55,
    stoppagesEn: [
      'Keraniganj',
      'New Market',
      'Farmgate',
      'Banani',
      'Uttara',
    ],
    stoppagesBn: [
      'কেরানীগঞ্জ',
      'নিউ মার্কেট',
      'ফার্মগেট',
      'বনানী',
      'উত্তরা',
    ],
  ),
  BusModel(
    nameEn: 'BRTC 34',
    nameBn: 'বিআরটিসি ৩৪',
    fromEn: 'Motijheel',
    fromBn: 'মতিঝিল',
    toEn: 'Abdullahpur',
    toBn: 'আব্দুল্লাহপুর',
    fare: 40,
    stoppagesEn: [
      'Motijheel',
      'Shahbag',
      'Farmgate',
      'Mohakhali',
      'Airport',
      'Abdullahpur',
    ],
    stoppagesBn: [
      'মতিঝিল',
      'শাহবাগ',
      'ফার্মগেট',
      'মহাখালী',
      'এয়ারপোর্ট',
      'আব্দুল্লাহপুর',
    ],
  ),
  BusModel(
    nameEn: 'Rajanigandha 35',
    nameBn: 'রজনীগন্ধা ৩৫',
    fromEn: 'Chittagong Road',
    fromBn: 'চিটাগং রোড',
    toEn: 'Mirpur 10',
    toBn: 'মিরপুর ১০',
    fare: 50,
    stoppagesEn: [
      'Chittagong Road',
      'Jatrabari',
      'Gulistan',
      'Farmgate',
      'Mirpur 10',
    ],
    stoppagesBn: [
      'চিটাগং রোড',
      'যাত্রাবাড়ী',
      'গুলিস্তান',
      'ফার্মগেট',
      'মিরপুর ১০',
    ],
  ),
  BusModel(
    nameEn: 'Taqwa 36',
    nameBn: 'তাকওয়া ৩৬',
    fromEn: 'Signboard',
    fromBn: 'সাইন বোর্ড',
    toEn: 'Mirpur 12',
    toBn: 'মিরপুর ১২',
    fare: 50,
    stoppagesEn: [
      'Signboard',
      'Kakrail',
      'Farmgate',
      'Agargaon',
      'Mirpur 12',
    ],
    stoppagesBn: [
      'সাইন বোর্ড',
      'কাকরাইল',
      'ফার্মগেট',
      'আগারগাঁও',
      'মিরপুর ১২',
    ],
  ),
  BusModel(
    nameEn: 'Victor 37',
    nameBn: 'ভিক্টর ৩৭',
    fromEn: 'Sadarghat',
    fromBn: 'সদরঘাট',
    toEn: 'Kuril',
    toBn: 'কুড়িল',
    fare: 40,
    stoppagesEn: [
      'Sadarghat',
      'Gulistan',
      'Malibagh',
      'Badda',
      'Kuril',
    ],
    stoppagesBn: [
      'সদরঘাট',
      'গুলিস্তান',
      'মালিবাগ',
      'বাড্ডা',
      'কুড়িল',
    ],
  ),
  BusModel(
    nameEn: 'Trust 38',
    nameBn: 'ট্রাস্ট ৩৮',
    fromEn: 'New Market',
    fromBn: 'নিউ মার্কেট',
    toEn: 'Nadda',
    toBn: 'নদ্দা',
    fare: 30,
    stoppagesEn: [
      'New Market',
      'Science Lab',
      'Farmgate',
      'Gulshan 1',
      'Nadda',
    ],
    stoppagesBn: [
      'নিউ মার্কেট',
      'সায়েন্স ল্যাব',
      'ফার্মগেট',
      'গুলশান ১',
      'নদ্দা',
    ],
  ),
  BusModel(
    nameEn: 'Midline 39',
    nameBn: 'মিডলাইন ৩৯',
    fromEn: 'Banasree',
    fromBn: 'বনশ্রী',
    toEn: 'Motijheel',
    toBn: 'মতিঝিল',
    fare: 25,
    stoppagesEn: [
      'Banasree',
      'Rampura',
      'Malibagh',
      'Kakrail',
      'Motijheel',
    ],
    stoppagesBn: [
      'বনশ্রী',
      'রামপুরা',
      'মালিবাগ',
      'কাকরাইল',
      'মতিঝিল',
    ],
  ),
  BusModel(
    nameEn: 'Anabil 40',
    nameBn: 'অনাবিল ৪০',
    fromEn: 'Gazipur',
    fromBn: 'গাজীপুর',
    toEn: 'Narayanganj',
    toBn: 'নারায়ণগঞ্জ',
    fare: 80,
    stoppagesEn: [
      'Gazipur',
      'Uttara',
      'Mohakhali',
      'Gulistan',
      'Jatrabari',
      'Narayanganj',
    ],
    stoppagesBn: [
      'গাজীপুর',
      'উত্তরা',
      'মহাখালী',
      'গুলিস্তান',
      'যাত্রাবাড়ী',
      'নারায়ণগঞ্জ',
    ],
  ),
];
